version: '3.7'

services:
  app:
    build: .
    ports:
      - "8080:80" 
    volumes:
      - ./:/var/www/my-yii2-app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    #  - ./apache.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yii2_pg
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: